CREATE TABLE IF NOT EXISTS SUBSCRIBERS
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id BIGINT                                  NOT NULL,
    post        VARCHAR                                 NOT NULL,
    initials    VARCHAR                                 NOT NULL,
    CONSTRAINT pk_subscriber PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DOCUMENTS
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_journal_id BIGINT                                  NOT NULL,
    date            DATE                                    NOT NULL,
    title           VARCHAR                                 NOT NULL,
    heading         VARCHAR                                 NOT NULL,
    document_number INTEGER                                 NOT NULL,
    document_status VARCHAR                                 NOT NULL,
    drawing_status  VARCHAR                                 NOT NULL,
    chief_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_document PRIMARY KEY (id),
    CONSTRAINT FK_DOCUMENTS_ON_SUBSCRIBERS FOREIGN KEY (chief_id) REFERENCES subscribers (id)
);

CREATE TABLE IF NOT EXISTS DOCUMENTS_SUBSCRIBERS
(
    document_id   BIGINT,
    subscriber_id BIGINT,
    CONSTRAINT pk_documents_of_subscribers PRIMARY KEY (document_id, subscriber_id)
);

CREATE TABLE IF NOT EXISTS REMARKS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    remark             VARCHAR                                 NOT NULL,
    inspector          VARCHAR                                 NOT NULL,
    document_corrected BOOLEAN                                 NOT NULL,
    document_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_remark PRIMARY KEY (id),
    CONSTRAINT FK_REMARKS_ON_DOCUMENTS FOREIGN KEY (document_id) REFERENCES documents (id)
);