CREATE TABLE IF NOT EXISTS EQUIPMENTS_TYPE
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_name VARCHAR                                 NOT NULL,
    volume         INTEGER,
    model          VARCHAR,
    CONSTRAINT pk_equipmentType PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS EQUIPMENTS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id BIGINT                                  NOT NULL,
    building_id       BIGINT                                  NOT NULL,
    equipment_name    VARCHAR                                 NOT NULL,
    stationary_number INTEGER,
    model             VARCHAR,
    volume            INTEGER,
    old               BOOLEAN,
    height            INTEGER,
    length            INTEGER,
    width             INTEGER,
    diameter          INTEGER,
    CONSTRAINT pk_equipment PRIMARY KEY (id),
    CONSTRAINT FK_EQUIPMENTS_ON_EQUIPMENTS_TYPE FOREIGN KEY (equipment_type_id) REFERENCES equipments_type (id)
);

CREATE TABLE IF NOT EXISTS EQUIPMENTS_PASSPORT
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id      BIGINT                                  NOT NULL,
    sequential_number INTEGER                                 NOT NULL,
    header            VARCHAR                                 NOT NULL,
    meaning           VARCHAR                                 NOT NULL,
    CONSTRAINT pk_equipmentPassport PRIMARY KEY (id),
    CONSTRAINT FK_EQUIPMENTS_ON_EQUIPMENTS_TYPE FOREIGN KEY (equipment_id) REFERENCES equipments (id)
);

CREATE TABLE IF NOT EXISTS STANDARD_SIZES
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    design_thickness DOUBLE PRECISION,
    outer_diameter   INTEGER,
    min_diameter     INTEGER,
    max_diameter     INTEGER,
    CONSTRAINT pk_standardSize PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ELEMENTS
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element_name     VARCHAR                                 NOT NULL,
    standard_size_id BIGINT,
    equipment_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_element PRIMARY KEY (id),
    CONSTRAINT FK_ELEMENTS_ON_STANDARD_SIZES FOREIGN KEY (standard_size_id) REFERENCES standard_sizes (id),
    CONSTRAINT FK_ELEMENTS_ON_EQUIPMENTS FOREIGN KEY (equipment_id) REFERENCES equipments (id)
);

CREATE TABLE IF NOT EXISTS PARTS_ELEMENTS
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    part_name        VARCHAR                                 NOT NULL,
    element_id       BIGINT                                  NOT NULL,
    standard_size_id BIGINT,
    CONSTRAINT pk_partElement PRIMARY KEY (id),
    CONSTRAINT FK_PARTS_ELEMENTS_ON_STANDARD_SIZES FOREIGN KEY (standard_size_id) REFERENCES standard_sizes (id),
    CONSTRAINT FK_PARTS_ELEMENTS_ON_ELEMENTS FOREIGN KEY (element_id) REFERENCES elements (id)
);