CREATE TABLE IF NOT EXISTS DOCUMENTATIONS
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    view   VARCHAR,
    number VARCHAR,
    title  VARCHAR                                 NOT NULL,
    path   VARCHAR,
    CONSTRAINT pk_documentation PRIMARY KEY (id),
    CONSTRAINT UQ_DOCUMENTATIONS UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS HEADER_DOCUMENTS
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR                                 NOT NULL,
    heading       VARCHAR                                 NOT NULL,
    type_document VARCHAR                                 NOT NULL,
    CONSTRAINT pk_headerDocument PRIMARY KEY (id),
    CONSTRAINT UQ_HEADER_DOCUMENTS UNIQUE (title, heading, type_document)
);

CREATE TABLE IF NOT EXISTS LABORATORY_EMPLOYEES
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR                                 NOT NULL,
    patronymic VARCHAR                                 NOT NULL,
    surname    VARCHAR                                 NOT NULL,
    post       VARCHAR                                 NOT NULL,
    CONSTRAINT pk_laboratoryEmployee PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CERTIFICATES
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type      VARCHAR                                 NOT NULL,
    certificate_number VARCHAR                                 NOT NULL,
    control_type       VARCHAR                                 NOT NULL,
    level              VARCHAR                                 NOT NULL,
    start_date         DATE                                    NOT NULL,
    end_date           DATE                                    NOT NULL,
    points             VARCHAR                                 NOT NULL,
    organization       VARCHAR                                 NOT NULL,
    employee_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_certificate PRIMARY KEY (id),
    CONSTRAINT UQ_CERTIFICATES UNIQUE (control_type, employee_id),
    CONSTRAINT FK_CERTIFICATE_ON_LABORATORY_EMPLOYEES FOREIGN KEY (employee_id) REFERENCES laboratory_employees (id)
);

CREATE TABLE IF NOT EXISTS TASKS_JOURNAL
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date               DATE                                    NOT NULL,
    branch_id          BIGINT                                  NOT NULL,
    branch             VARCHAR                                 NOT NULL,
    building_id        BIGINT                                  NOT NULL,
    building           VARCHAR                                 NOT NULL,
    address_id         BIGINT                                  NOT NULL,
    address            VARCHAR                                 NOT NULL,
    equipment_id       BIGINT                                  NOT NULL,
    equipment          VARCHAR                                 NOT NULL,
    chief_id           BIGINT                                  NOT NULL,
    task_source        VARCHAR,
    comment            VARCHAR,
    status             VARCHAR                                 NOT NULL,
    document_id        BIGINT,
    header_document_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_tasksJournal PRIMARY KEY (id),
    CONSTRAINT FK_TASKS_JOURNAL_ON_LABORATORY_EMPLOYEES FOREIGN KEY (chief_id) REFERENCES laboratory_employees (id),
    CONSTRAINT FK_TASKS_JOURNAL_ON_HEADER_DOCUMENTS FOREIGN KEY (header_document_id) REFERENCES header_documents (id)
);

CREATE TABLE IF NOT EXISTS TASKS_JOURNAL_EMPLOYEES
(
    task_id     BIGINT,
    employee_id BIGINT,
    CONSTRAINT pk_tasks_journal_of_laboratory_employees PRIMARY KEY (task_id, employee_id)
);

CREATE TABLE IF NOT EXISTS MEASURING_TOOLS
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    toll                   VARCHAR                                 NOT NULL,
    model                  VARCHAR                                 NOT NULL,
    work_number            VARCHAR,
    purpose                VARCHAR,
    manufacturing          DATE,
    exploitation           DATE,
    manufacturer           VARCHAR,
    measuring_range        VARCHAR,
    characteristics        VARCHAR,
    owner                  VARCHAR                                 NOT NULL,
    verification_date      DATE,
    next_verification_date DATE,
    organization           VARCHAR,
    certificate_number     VARCHAR,
    registry               VARCHAR,
    note                   VARCHAR,
    control_type           VARCHAR                                 NOT NULL,
    employee_id            BIGINT,
    CONSTRAINT pk_measuringTool PRIMARY KEY (id),
    CONSTRAINT UQ_MEASURING_TOOL UNIQUE (toll, model, work_number),
    CONSTRAINT FK_MEASURING_TOOL_ON_LABORATORY_EMPLOYEES FOREIGN KEY (employee_id) REFERENCES laboratory_employees (id)
);