CREATE TABLE IF NOT EXISTS EQUIPMENTS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name         VARCHAR                                 NOT NULL,
    short_name        VARCHAR                                 NOT NULL,
    stationary_number INTEGER,
    model             VARCHAR,
    volume            INTEGER,
    building_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_equipment PRIMARY KEY (id),
    CONSTRAINT FK_EQUIPMENTS_ON_BUILDINGS FOREIGN KEY (building_id) REFERENCES buildings (id)
);

CREATE TABLE IF NOT EXISTS LICENSES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type     VARCHAR                                 NOT NULL,
    license_number    VARCHAR                                 NOT NULL,
    start_data        DATE                                    NOT NULL,
    end_data          DATE                                    NOT NULL,
    issued_license_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_licenses PRIMARY KEY (id),
    CONSTRAINT UQ_LICENSES UNIQUE (license_number, start_data, end_data)
);

CREATE TABLE IF NOT EXISTS ORGANIZATIONS_LICENSES
(
    organization_id BIGINT,
    license_id      BIGINT,
    CONSTRAINT pk_organizations_of_licenses PRIMARY KEY (organization_id, license_id)
);

CREATE TABLE IF NOT EXISTS BRANCHES_LICENSES
(
    branch_id  BIGINT,
    license_id BIGINT,
    CONSTRAINT pk_branches_of_licenses PRIMARY KEY (branch_id, license_id)
);

CREATE TABLE IF NOT EXISTS DEPARTMENTS_LICENSES
(
    department_id BIGINT,
    license_id    BIGINT,
    CONSTRAINT pk_departments_of_licenses PRIMARY KEY (department_id, license_id)
);

CREATE TABLE IF NOT EXISTS CONTACTS
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone VARCHAR,
    fax   VARCHAR,
    email VARCHAR,
    CONSTRAINT pk_contact PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PLACE_WORKS
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id        BIGINT                                  NOT NULL,
    branch_id              BIGINT                                  NOT NULL,
    department_id          BIGINT,
    exploitation_region_id BIGINT,
    building_id            BIGINT,
    CONSTRAINT pk_placeWork PRIMARY KEY (id),
    CONSTRAINT FK_PLACE_WORKS_ON_ORGANIZATIONS FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT FK_PLACE_WORKS_ON_BRANCHES FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT FK_PLACE_WORKS_ON_DEPARTMENTS FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT FK_PLACE_WORKS_ON_EXPLOITATION_REGIONS FOREIGN KEY (exploitation_region_id)
        REFERENCES exploitation_regions (id),
    CONSTRAINT FK_PLACE_WORKS_ON_BUILDINGS FOREIGN KEY (building_id) REFERENCES buildings (id)
);

CREATE TABLE IF NOT EXISTS EMPLOYEES
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR                                 NOT NULL,
    patronymic    VARCHAR                                 NOT NULL,
    surname       VARCHAR                                 NOT NULL,
    post          VARCHAR                                 NOT NULL,
    contact_id    BIGINT,
    place_work_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (id),
    CONSTRAINT UQ_EMPLOYEES UNIQUE (name, patronymic, surname),
    CONSTRAINT FK_EMPLOYEES_ON_CONTACTS FOREIGN KEY (contact_id) REFERENCES contacts (id),
    CONSTRAINT FK_EMPLOYEES_ON_PLACE_WORKS FOREIGN KEY (place_work_id) REFERENCES place_works (id)
);