CREATE TABLE IF NOT EXISTS ADDRESSES
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    index           INTEGER,
    city            VARCHAR                                 NOT NULL,
    street          VARCHAR                                 NOT NULL,
    house_number    INTEGER                                 NOT NULL,
    building_number INTEGER,
    letter          VARCHAR,
    CONSTRAINT pk_address PRIMARY KEY (id),
    CONSTRAINT UQ_ADDRESSES UNIQUE (city, street, house_number, building_number, letter)
);

CREATE TABLE IF NOT EXISTS DIVISION_CONTACTS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR                                 NOT NULL,
    patronymic VARCHAR                                 NOT NULL,
    surname    VARCHAR                                 NOT NULL,
    post       VARCHAR                                 NOT NULL,
    phone      VARCHAR,
    fax        VARCHAR,
    email      VARCHAR,
    CONSTRAINT pk_divisionContact PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ORGANIZATIONS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR                                 NOT NULL,
    short_name VARCHAR                                 NOT NULL,
    address_id BIGINT                                  NOT NULL,
    contact_id BIGINT,
    CONSTRAINT pk_organization PRIMARY KEY (id),
    CONSTRAINT UQ_ORGANIZATIONS UNIQUE (full_name, short_name),
    CONSTRAINT FK_ORGANIZATIONS_ON_ADDRESSES FOREIGN KEY (address_id) REFERENCES addresses (id),
    CONSTRAINT FK_ORGANIZATIONS_ON_DIVISION_CONTACTS FOREIGN KEY (contact_id) REFERENCES division_contacts (id)
);

CREATE TABLE IF NOT EXISTS BRANCHES
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name       VARCHAR                                 NOT NULL,
    short_name      VARCHAR                                 NOT NULL,
    address_id      BIGINT                                  NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    contact_id BIGINT,
    CONSTRAINT pk_branch PRIMARY KEY (id),
    CONSTRAINT UQ_BRANCHES UNIQUE (full_name, short_name),
    CONSTRAINT FK_BRANCHES_ON_ORGANIZATIONS FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT FK_BRANCHES_ON_ADDRESSES FOREIGN KEY (address_id) REFERENCES addresses (id),
    CONSTRAINT FK_BRANCHES_ON_DIVISION_CONTACTS FOREIGN KEY (contact_id) REFERENCES division_contacts (id)
);

CREATE TABLE IF NOT EXISTS HEAT_SUPPLY_AREAS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR                                 NOT NULL,
    short_name VARCHAR                                 NOT NULL,
    branch_id  BIGINT                                  NOT NULL,
    contact_id BIGINT,
    CONSTRAINT pk_heatSupplyArea PRIMARY KEY (id),
    CONSTRAINT UQ_HEAT_SUPPLY_AREAS UNIQUE (full_name, short_name),
    CONSTRAINT FK_HEAT_SUPPLY_AREAS_ON_BRANCHES FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT FK_HEAT_SUPPLY_AREAS_ON_DIVISION_CONTACTS FOREIGN KEY (contact_id) REFERENCES division_contacts (id)
);

CREATE TABLE IF NOT EXISTS EXPLOITATION_REGIONS
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name           VARCHAR                                 NOT NULL,
    short_name          VARCHAR                                 NOT NULL,
    number              INTEGER                                 NOT NULL,
    heat_supply_area_id BIGINT                                  NOT NULL,
    contact_id BIGINT,
    CONSTRAINT pk_exploitationRegion PRIMARY KEY (id),
    CONSTRAINT UQ_EXPLOITATION_REGIONS UNIQUE (full_name, short_name),
    CONSTRAINT FK_EXPLOITATION_REGIONS_ON_HEAT_SUPPLY_AREAS
        FOREIGN KEY (heat_supply_area_id) REFERENCES heat_supply_areas (id),
    CONSTRAINT FK_EXPLOITATION_REGIONS_ON_DIVISION_CONTACTS FOREIGN KEY (contact_id) REFERENCES division_contacts (id)
);

CREATE TABLE IF NOT EXISTS BUILDINGS
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    building_type VARCHAR                                 NOT NULL,
    login         VARCHAR,
    region_id     BIGINT                                  NOT NULL,
    address_id    BIGINT                                  NOT NULL,
    contact_id BIGINT,
    CONSTRAINT pk_building PRIMARY KEY (id),
    CONSTRAINT UQ_BUILDINGS UNIQUE (building_type, login),
    CONSTRAINT FK_BUILDINGS_ON_ADDRESSES FOREIGN KEY (address_id) REFERENCES addresses (id),
    CONSTRAINT FK_BUILDINGS_ON_EXPLOITATION_REGIONS FOREIGN KEY (region_id) REFERENCES exploitation_regions (id),
    CONSTRAINT FK_BUILDINGS_ON_DIVISION_CONTACTS FOREIGN KEY (contact_id) REFERENCES division_contacts (id)
);


CREATE TABLE IF NOT EXISTS DEPARTMENTS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR                                 NOT NULL,
    short_name VARCHAR                                 NOT NULL,
    address_id BIGINT                                  NOT NULL,
    branch_id  BIGINT                                  NOT NULL,
    contact_id BIGINT,
    CONSTRAINT pk_department PRIMARY KEY (id),
    CONSTRAINT UQ_DEPARTMENTS UNIQUE (full_name, short_name),
    CONSTRAINT FK_DEPARTMENTS_ON_ADDRESSES FOREIGN KEY (address_id) REFERENCES addresses (id),
    CONSTRAINT FK_DEPARTMENTS_ON_DIVISION_CONTACTS FOREIGN KEY (contact_id) REFERENCES division_contacts (id)
);

CREATE TABLE IF NOT EXISTS LICENSES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type     VARCHAR                                 NOT NULL,
    license_number    VARCHAR                                 NOT NULL,
    start_data        DATE                                    NOT NULL,
    end_data          DATE                                    NOT NULL,
    issued_license_id BIGINT                                  NOT NULL,
    organization_id   BIGINT,
    branch_id         BIGINT,
    department_id     BIGINT,
    CONSTRAINT pk_licenses PRIMARY KEY (id),
    CONSTRAINT UQ_LICENSES UNIQUE (license_number, start_data, end_data),
    CONSTRAINT FK_LICENSES_ON_ORGANIZATIONS FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT FK_LICENSES_ON_BRANCHES FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT FK_LICENSES_ON_DEPARTMENTS FOREIGN KEY (department_id) REFERENCES departments (id)
);

CREATE TABLE IF NOT EXISTS CONTACTS
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone VARCHAR,
    fax   VARCHAR,
    email VARCHAR,
    CONSTRAINT pk_contact PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PLACE_WORKS
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id        BIGINT                                  NOT NULL,
    branch_id              BIGINT                                  NOT NULL,
    department_id          BIGINT,
    exploitation_region_id BIGINT,
    building_id            BIGINT,
    CONSTRAINT pk_placeWork PRIMARY KEY (id),
    CONSTRAINT FK_PLACE_WORKS_ON_ORGANIZATIONS FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT FK_PLACE_WORKS_ON_BRANCHES FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT FK_PLACE_WORKS_ON_DEPARTMENTS FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT FK_PLACE_WORKS_ON_EXPLOITATION_REGIONS FOREIGN KEY (exploitation_region_id)
        REFERENCES exploitation_regions (id),
    CONSTRAINT FK_PLACE_WORKS_ON_BUILDINGS FOREIGN KEY (building_id) REFERENCES buildings (id)
);

CREATE TABLE IF NOT EXISTS EMPLOYEES
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR                                 NOT NULL,
    patronymic    VARCHAR                                 NOT NULL,
    surname       VARCHAR                                 NOT NULL,
    post          VARCHAR                                 NOT NULL,
    contact_id    BIGINT,
    place_work_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (id),
    CONSTRAINT UQ_EMPLOYEES UNIQUE (name, patronymic, surname),
    CONSTRAINT FK_EMPLOYEES_ON_CONTACTS FOREIGN KEY (contact_id) REFERENCES contacts (id),
    CONSTRAINT FK_EMPLOYEES_ON_PLACE_WORKS FOREIGN KEY (place_work_id) REFERENCES place_works (id)
);