CREATE TABLE IF NOT EXISTS COLUMNS_HEADERS_TEMPLATES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number INTEGER                                 NOT NULL,
    heading           VARCHAR                                 NOT NULL,
    column_data_type  VARCHAR                                 NOT NULL,
    CONSTRAINT pk_columnHeader PRIMARY KEY (id),
    CONSTRAINT UQ_COLUMNS_HEADERS_TEMPLATES UNIQUE (sequential_number, heading)
);

CREATE TABLE IF NOT EXISTS DIVISION_DATA
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    division_name VARCHAR,
    address       VARCHAR,
    license       VARCHAR,
    contacts      VARCHAR,
    CONSTRAINT pk_divisionData PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS HEADER_TEMPLATES
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    header_document_id BIGINT                                  NOT NULL,
    organization_id    BIGINT,
    branch_id          BIGINT,
    department_id      BIGINT,
    area_id            BIGINT,
    region_id          BIGINT,
    CONSTRAINT pk_headerTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_HEADER_TEMPLATES UNIQUE (header_document_id),
    CONSTRAINT FK_HEADER_TEMPLATES_ON_DIVISION_DATA
        FOREIGN KEY (organization_id) REFERENCES division_data (id),
    FOREIGN KEY (branch_id) REFERENCES division_data (id),
    FOREIGN KEY (department_id) REFERENCES division_data (id),
    FOREIGN KEY (area_id) REFERENCES division_data (id),
    FOREIGN KEY (region_id) REFERENCES division_data (id)
);

CREATE TABLE IF NOT EXISTS CONCLUSION_TEMPLATES
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    header_text  VARCHAR                                 NOT NULL,
    if_than_norm VARCHAR,
    approaching  VARCHAR,
    equal        VARCHAR,
    if_less_norm VARCHAR,
    if_no_norm   VARCHAR,
    CONSTRAINT pk_conclusionTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_CONCLUSION_TEMPLATES UNIQUE (header_text)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_TEMPLATES
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_document_id       BIGINT                                  NOT NULL,
    equipment_type_id      BIGINT                                  NOT NULL,
    title                  VARCHAR                                 NOT NULL,
    heading                VARCHAR                                 NOT NULL,
    header_id              BIGINT                                  NOT NULL,
    conclusion_template_id BIGINT,
    CONSTRAINT pk_protocolTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_PROTOCOL_TEMPLATES UNIQUE (type_document_id, equipment_type_id),
    CONSTRAINT FK_PROTOCOL_TEMPLATES_ON_HEADER_TEMPLATES FOREIGN KEY (header_id) REFERENCES header_templates (id),
    CONSTRAINT FK_PROTOCOL_TEMPLATES_ON_CONCLUSION_TEMPLATES
        FOREIGN KEY (conclusion_template_id) REFERENCES conclusion_templates (id)
);

CREATE TABLE IF NOT EXISTS TABLE_TEMPLATES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number INTEGER,
    table_name        VARCHAR,
    text_before_table VARCHAR,
    text_after_table  VARCHAR,
    table_data_type   VARCHAR                                 NOT NULL,
    protocol_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_tableTemplate PRIMARY KEY (id),
    CONSTRAINT FK_TABLE_TEMPLATES_ON_PROTOCOL_TEMPLATES FOREIGN KEY (protocol_id) REFERENCES protocol_templates (id)
);

CREATE TABLE IF NOT EXISTS TABLE_COLUMNS_HEADERS_TEMPLATES
(
    table_id          BIGINT,
    columns_header_id BIGINT,
    CONSTRAINT pk_table_templates_of_columns_headers_templates PRIMARY KEY (table_id, columns_header_id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_TEMPLATES
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number         DOUBLE PRECISION                        NOT NULL,
    subsection_name           VARCHAR                                 NOT NULL,
    user_text                 VARCHAR,
    sequential_number_visible BOOLEAN                                 NOT NULL,
    certificate_employee      VARCHAR,
    division_data             VARCHAR,
    table_id                  BIGINT,
    type_document             VARCHAR,
    protocol_conclusion       BOOLEAN,
    auto_table                BOOLEAN,
    protocol_id               BIGINT,
    CONSTRAINT pk_subsectionTemplate PRIMARY KEY (id),
    CONSTRAINT FK_SUBSECTION_TEMPLATES_ON_TABLE_TEMPLATES FOREIGN KEY (table_id) REFERENCES table_templates (id),
    CONSTRAINT FK_SUBSECTION_TEMPLATES_ON_PROTOCOL_TEMPLATES FOREIGN KEY (protocol_id) REFERENCES protocol_templates (id)
);

CREATE TABLE IF NOT EXISTS DOCUMENTATION_TEMPLATES
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR                                 NOT NULL,
    CONSTRAINT pk_documentationTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS MEASURING_TOOL_TEMPLATES
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR                                 NOT NULL,
    CONSTRAINT pk_measuringToolTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_DOCUMENTATION_TEMPLATES
(
    subsection_id    BIGINT,
    documentation_id BIGINT,
    CONSTRAINT pk_subsection_templates_of_documentation_templates PRIMARY KEY (subsection_id, documentation_id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_MEASURING_TOOLS_TEMPLATES
(
    subsection_id BIGINT,
    tool_id       BIGINT,
    CONSTRAINT pk_subsection_templates_of_measuring_tool_templates PRIMARY KEY (subsection_id, tool_id)
);

CREATE TABLE IF NOT EXISTS PAGE_TITLE_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    header_id             BIGINT                                  NOT NULL,
    title                 VARCHAR                                 NOT NULL,
    heading               VARCHAR                                 NOT NULL,
    equipment             VARCHAR,
    installation_location VARCHAR,
    address               VARCHAR,
    post                  VARCHAR,
    employee              VARCHAR,
    city                  VARCHAR,
    CONSTRAINT pk_pageTitleTemplate PRIMARY KEY (id),
    CONSTRAINT FK_PAGE_TITLE_TEMPLATES_ON_HEADER_TEMPLATES FOREIGN KEY (header_id) REFERENCES header_templates (id)
);

CREATE TABLE IF NOT EXISTS REPORT_TEMPLATES
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    header_document_id BIGINT                                  NOT NULL,
    equipment_type_id  BIGINT                                  NOT NULL,
    page_title_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_reportTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_REPORT_TEMPLATES UNIQUE (header_document_id, equipment_type_id),
    CONSTRAINT FK_REPORT_TEMPLATES_ON_PAGE_TITLE_TEMPLATES
        FOREIGN KEY (page_title_id) REFERENCES page_title_templates (id)
);

CREATE TABLE IF NOT EXISTS APPENDICES_TEMPLATES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number INTEGER                                 NOT NULL,
    appendices_name   VARCHAR                                 NOT NULL,
    report_id         BIGINT                                  NOT NULL,
    protocol_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_appendicesTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_APPENDICES_TEMPLATES UNIQUE (sequential_number, appendices_name),
    CONSTRAINT FK_APPENDICES_TEMPLATES_ON_REPORT_TEMPLATES FOREIGN KEY (report_id) REFERENCES report_templates (id),
    CONSTRAINT FK_APPENDICES_TEMPLATES_ON_PROTOCOL_TEMPLATES FOREIGN KEY (protocol_id) REFERENCES protocol_templates (id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOL_TEMPLATES
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    header_document_id      BIGINT                                  NOT NULL,
    title                   VARCHAR                                 NOT NULL,
    heading                 VARCHAR                                 NOT NULL,
    sequential_number       INTEGER                                 NOT NULL,
    user_text_after_heading VARCHAR,
    conclusion_template_id  BIGINT,
    report_id               BIGINT                                  NOT NULL,
    CONSTRAINT FK_SECTION_TEMPLATES_ON_REPORT_TEMPLATES FOREIGN KEY (report_id) REFERENCES report_templates (id),
    CONSTRAINT pk_reportProtocolTemplate PRIMARY KEY (id),
    CONSTRAINT FK_REPORT_PROTOCOL_TEMPLATES_ON_CONCLUSION_TEMPLATES
        FOREIGN KEY (conclusion_template_id) REFERENCES conclusion_templates (id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOL_SUBSECTION_TEMPLATES
(
    protocol_id   BIGINT,
    subsection_id BIGINT,
    CONSTRAINT pk_report_protocol_templates_of_subsection_templates PRIMARY KEY (protocol_id, subsection_id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOL_TABLE_TEMPLATES
(
    protocol_id BIGINT,
    table_id    BIGINT,
    CONSTRAINT pk_report_protocol_templates_of_table_templates PRIMARY KEY (protocol_id, table_id)
);

CREATE TABLE IF NOT EXISTS SECTION_TEMPLATES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number INTEGER                                 NOT NULL,
    section_name      VARCHAR                                 NOT NULL,
    report_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_sectionTemplate PRIMARY KEY (id),
    CONSTRAINT FK_SECTION_TEMPLATES_ON_REPORT_TEMPLATES FOREIGN KEY (report_id) REFERENCES report_templates (id)
);

CREATE TABLE IF NOT EXISTS SECTION_SUBSECTION_TEMPLATES
(
    section_id    BIGINT,
    subsection_id BIGINT,
    CONSTRAINT pk_section_templates_of_subsection_templates PRIMARY KEY (section_id, subsection_id)
);

CREATE TABLE IF NOT EXISTS SECTION_PROTOCOL_TEMPLATES
(
    section_id  BIGINT,
    protocol_id BIGINT,
    CONSTRAINT pk_section_templates_of_report_protocol_templates PRIMARY KEY (section_id, protocol_id)
);